export const plans = [
  {
    key: "premium",
    name: "Premium",
    price: "₹999/mo",
    description: "Access to full photo library and premium features.",
    features: [
      "Full photo library access",
      "Zomato-compliant photos",
      "Unlimited downloads",
      "Priority photo request handling",
      "Exclusive new photo collections every month",
      "Early access to new features",
      "Access to seasonal & trending food photo packs",
      "High-quality images",
    ],
    button: "Go Premium",
    link: "/payment/cart?plan=premium",
    highlight: true,
    duration: 30,
    renewPrice: 899,
    amount: 1999,
    discountedAmount: 999,
    discountPercentage: 50,
    taxPercentage: 18,
  },
];

export const services = [
  {
    key: "food-license",
    name: "Food License Assistance",
    price: "₹700",
    description:
      "Assistance with food license application paperwork and submission guidance so you get compliant quickly.",
    features: [
      "Consultation on required documents",
      "Fillable form guidance & template support",
      "Checklist for local inspection readiness",
      "Submission guidance and follow-up tips",
      "Email support for application queries",
    ],
    button: "Get License Help",
    link: "/payment/cart?plan=food-license",
    highlight: false,
    duration: 0,
    renewPrice: 0,
    amount: 1499,
    discountedAmount: 700,
    discountPercentage: 50,
    taxPercentage: 18,
  },
  {
    key: "zomato-swiggy-setup",
    name: "Complete Zomato + Swiggy Setup",
    price: "₹3000",
    description:
      "End-to-end onboarding: account creation, menu uploading, photo optimization, and full platform setup for both Zomato & Swiggy.",
    features: [
      "Create/claim Zomato & Swiggy accounts",
      "End-to-end menu upload (titles, descriptions, prices)",
      "Image selection & Zomato-compliant resizing",
      "Category & cuisine mapping",
      "Basic SEO for menu items",
      "Verification guidance and onboarding support",
      "1 follow-up to fix issues after go-live",
      "Training on how to manage menu & images",
      "Monthly menu updates for first month (unlimited rate/item changes)",
      "Ads & offers strategy guidance for first month",
    ],
    button: "Buy Setup",
    link: "/payment/cart?plan=zomato-swiggy-setup",
    highlight: true,
    duration: 0,
    renewPrice: 0,
    amount: 5999,
    discountedAmount: 3000,
    discountPercentage: 50,
    taxPercentage: 18,
  },

  {
    key: "menu-transfer",
    name: "Menu Transfer (Zomato ↔ Swiggy)",
    price: "₹1000",
    description:
      "Transfer or clone full menu between Zomato and Swiggy (or Zomato→Zomato) including images, pricing, and categories. Includes one month of menu updates and ads/offers guidance.",
    features: [
      "Full menu export & import",
      "Image mapping to destination platform",
      "Price & category reconciliation",
      "Fixes for platform-specific validation errors",
      "Post-transfer verification (1 round)",
      "Monthly menu updates for first month (unlimited rate/item changes)",
      "Ads & offers strategy guidance for first month",
    ],
    button: "Transfer Menu",
    link: "/payment/cart?plan=menu-transfer",
    highlight: false,
    duration: 0,
    renewPrice: 0,
    amount: 1999,
    discountedAmount: 1000,
    discountPercentage: 50,
    taxPercentage: 18,
  },
];
